### ISSUE TITLE
WNWordDefinitionRequest requires a WNDictionary

### ISSUE THREAD

**Issue by chrisdoble** [wordnik/wordkit#6]
The docs state that you can create a `WNWordDefinitionRequest` and pass `nil` for the dictionary, making it consult all available dictionaries. I haven't been able to get this working; it just throws an `NSInternalInconsistencyException` with the reason being `The dictionary parameter may not be nil`.

Both of the following recreate the issue:

```
[WNWordDefinitionRequest requestWithDictionary:nil];
[[[WNWordDefinitionRequest alloc] initWithDictionary:nil partsOfSpeech:nil
    maxResultCount:WNUnlimitedResultLength] autorelease];
```

**Comment by fehguy** [comment]
Hi Chrisdoble, I believe this is a doc bug.  Fetching a definition for a word with explicit dictionary type nil doesn't make sense--I'll look at correcting the docs.

The default behavior is to consult all dictionaries and pick the first one with definitions.  You're looking for something different, meaning, you want definitions from _all_ dictionaries, is that correct?

**Comment by chrisdoble** [comment]
Nope, I'm just after the default behaviour as you describe:

> The default behavior is to consult all dictionaries and pick the first one with definitions.

The problem is I can't create a `WNWordDefinitionRequest` without providing a `WNDictionary`. You don't need to provide a `sourceDictionaries` value when making a request to `/word.{format}/{word}/definitions`, but you _must_ in Wordkit.

Any of the following would solve the problem—they're all just saying "I don't care where the definitions come from, just get the first":

```
[WNWordDefinitionRequest request];
[WNWordDefinitionRequest requestWithDictionary:nil];
[WNWordDefinitionRequest requestWithDictionary:[WNDictionary allDictionaries]];
```

Perhaps (hopefully) I've just missed something and it's already possible to do this.

**Comment by fehguy** [comment]
ah!  It had a defect.  I've just fixed the issue and updated the version to 1.02.  Can you please try and let me know how it goes?  You can now pass nil as the dictionary.

**Comment by chrisdoble** [comment]
That fixed it, thanks!

This has spawned a somewhat related issue: when you pass `nil` to a `WNWordDefinitionRequest`, the `sourceDictionary` property of all the returned `WNDefinitionList`s is `nil`. This means that you can't determine where the definitions came from. It seems as though the `/word.{format}/{word}/definitions` endpoint always returns this information.

This isn't something that's going to affect me any time soon, I just thought I'd bring it to your attention.

**Comment by fehguy** [comment]
Great--and yes, that dictionary name is a defect.  We'll address that and add more functionality to the library shortly.  Also looking to make it substantially easier to use.
